# version 代表的是 compose file format 版本，
# 具体可以查阅官网：https://docs.docker.com/compose/compose-file/ 
version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli
    environment:
      MICRO_REGISTRY: "mdns"

  user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "localhost:27017"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "localhost:27017"

  user-service:
    build: ./user-service
    ports:
      - 50053:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"

  datastore:
    image: mongo
    ports:
      - 27017:27017

  database:
    image: postgres
    ports:
      - 5432:5432